version: '3.8'

services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ponto_inteligente
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: H@123Cop$
volumes:
  postgres_data:
